default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: crunchyroll_dlp_api_development

test:
  <<: *default
  database: crunchyroll_dlp_api_test

production:
  <<: *default
  database: crunchyroll_dlp_api_production
  username: crunchyroll_dlp_api
  password: <%= ENV["CRUNCHYROLL_DLP_API_DATABASE_PASSWORD"] %>
